export {
  GraphQLJSON as JSON,
  GraphQLJSONObject as JSONObject,
  GraphQLURL as URL,
  GraphQLDate as Date,
  GraphQLDateTime as DateTime,
  GraphQLEmailAddress as EmailAddress,
  GraphQLHexColorCode as HexColorCode,
  GraphQLHSL as HSL,
  GraphQLHSLA as HSLA,
  GraphQLRGB as RGB,
  GraphQLRGBA as RGBA,
  GraphQLObjectID as ObjectID,
  GraphQLTime as Time,
  GraphQLTimestamp as Timestamp,
  GraphQLVoid as Void,
} from 'graphql-scalars';
